[package]
name = "window"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
console_error_panic_hook = "0.1.7"
iced = { workspace = true }
iced_auravibe = { path = "../../uikit" }

[lints]
workspace = true
